#!/bin/bash

## Files and cmd
FILE="$HOME/.cache/eww_launch.xyz"
EWW="eww"

## Run eww daemon if not running already
if [[ ! `pidof eww` ]]; then
	${EWW} daemon
	sleep 1
fi

## Open widgets 
run_eww() {
	${EWW} open-many \
		   background \
		   profile \
		   system \
		   clock \
		   uptime \
		   music \
		   github \
		   reddit \
		   twitter \
		   youtube \
		   weather \
		   apps \
		   mail \
		   logout \
		   sleep \
		   reboot \
		   poweroff \
		   folders
}


## Open widgets 
run_ewww() {
	${EWW} open-many \
		   background \
		   profile 
}

## Launch or close widgets accordingly
if [[ ! -f "$FILE" ]]; then
	touch "$FILE"
	run_ewww
else
	${EWW} close-all
	rm "$FILE"
fi
